# Sub-configs
source=~/.config/mango/monitor.conf
source=~/.config/mango/input.conf
source=~/.config/mango/bindings.conf
source=~/.config/mango/mango.conf
source=~/.config/mango/autostart.conf
source=~/.config/mango/windowrules.conf
