# Window rules
windowrule=animation_type_open:none,appid:org.fagram
windowrule=animation_type_close:none,appid:org.fagram
windowrule=noblur:1,appid:org.fagram

# Layer rules
layerrule=noblur:1,layer_name:selection

# Games
allow_tearing=1
windowrule=force_tearing:1,title=vkcube
windowrule=force_tearing:1,isfullscreen:1,title=Counter-Strike 2
windowrule=force_tearing:1,isfullscreen:1,title=THE FINALS
windowrule=force_tearing:1,isfullscreen:1,title=Arc Raiders
windowrule=force_tearing:1,isfullscreen:1,title=Deep Rock Galactic
windowrule=force_tearing:1,isfullscreen:1,title=HELLDIVERS™ 2
